kinds = (
    ("symbol-file", None),             
    ("symbol-module", None),           
    ("symbol-namespace", None),        
    ("symbol-package", None),          
    ("symbol-class", "#de9327"),            
    ("symbol-method", "#AB7CCF"),           
    ("symbol-property", "#6eb1ee"),         
    ("symbol-field", "#6eb1ee"),            
    ("symbol-constructor", "#6eb1ee"),      
    ("symbol-enum", None),             
    ("symbol-interface", "#de9327"),        
    ("symbol-function", "#AB7CCF"),         
    ("symbol-variable", "#6eb1ee"),         
    ("symbol-constant", None),         
    ("symbol-string", None),           
    ("symbol-number", None),           
    ("symbol-boolean", "#de9327"),          
    ("symbol-array", None),            
    ("symbol-object", None),           
    ("symbol-key", None),              
    ("symbol-null", None),             
    ("symbol-enum-member", None),      
    ("symbol-struct", None),           
    ("symbol-event", "#ffd700"),            
    ("symbol-operator", None),         
    ("symbol-type-parameter", "#ffd700")
)
