kinds = (
    ("symbol-file", None),
    ("symbol-file", None),
    ("symbol-namespace", None),
    ("package", None),
    ("symbol-class", "#de9327"),
    ("symbol-method", "#AB7CCF"),
    ("symbol-property", "#6eb1ee"),
    ("symbol-field", "#6eb1ee"),
    ("symbol-method", "#6eb1ee"),
    ("symbol-enum", None),
    ("symbol-interface", "#de9327"),
    ("symbol-method", "#AB7CCF"),
    ("symbol-variable", "#6eb1ee"),
    ("symbol-constant", None),
    ("symbol-string", None),
    ("symbol-numeric", None),
    ("symbol-boolean", "#de9327"),
    ("symbol-array", None),
    ("symbol-class", None),
    ("symbol-key", None),
    ("symbol-misc", None),
    ("symbol-enum-member", None),
    ("symbol-structure", None),
    ("symbol-event", "#ffd700"),
    ("symbol-operator", None),
    ("symbol-parameter", "#ffd700"),
)
